_welcome:
    pattern:  /
    defaults: { _controller: CalendarCalendarBundle:Default:index }

_wdt:
    resource: "@WebProfilerBundle/Resources/config/routing/wdt.xml"
    prefix:   /_wdt

_profiler:
    resource: "@WebProfilerBundle/Resources/config/routing/profiler.xml"
    prefix:   /_profiler

_configurator:
    resource: "@SensioDistributionBundle/Resources/config/routing/webconfigurator.xml"
    prefix:   /_configurator

_main:
    resource: routing.yml

login:
  pattern: /login
  defaults: { _controller: CalendarSecurityBundle:Default:login }
logout:
  pattern: /logout
  defaults: { _controller: CalendarSecurityBundle:Default:logout }

login_check:
    pattern: /login_check

create_user:
    pattern: /
