security:
    firewalls:
        secured_area:
            pattern:    ^/
            anonymous: ~
            form_login:
                login_path:  login
                check_path:  login_check
                always_use_default_target_path: true
                default_target_path: /
            logout:
                path:   /logout
        login_firewall:
            pattern:    ^/login$
            anonymous:  ~
    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_USER }
    providers:
        users:
            entity: { class: CalendarCalendarBundle:User, property: userName }
#            in_memory:
#                memory:
#                    users:
#                        ryan:  { password: ryanpass, roles: 'ROLE_USER' }
#                        admin: { password: kitten, roles: 'ROLE_ADMIN' }

    encoders:
        Calendar\CalendarBundle\Entity\User:
            algorithm:        sha1
            encode_as_base64: false
            iterations:       1
#        Symfony\Component\Security\Core\User\User: plaintext

